name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # ⬇️ Désactive Rollup natif pour TOUTES les étapes du job
    env:
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          # ⚠️ Pas de cache npm pour éviter de garder un lock cassé
          check-latest: true

      # 🔥 Nettoyage complet avant installation
      - name: Clean workspace
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install deps (fresh)
        run: npm install --no-audit --no-fund

      - name: Verify env for Rollup
        run: |
          node -v
          npm -v
          echo "ROLLUP_SKIP_NODEJS_NATIVE=$ROLLUP_SKIP_NODEJS_NATIVE"

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
